server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  # 网关路由配置
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由。一个微服务可以有多个提供者，这样就实现了负载军和
      routes:
        - id: payment_routh           # 路由的ID
          uri: lb://cloud-payment-service
          # uri: http://localhost:8001  # predicate匹配之后，提供服务的路由地址
          predicates:
            - Path=/payment/get/**    # 断言，路径相匹配的用对应的uri进行路由

        - id: payment_routh2
          uri: lb://cloud-payment-service
          # uri: http:/localhost:8001
          predicates:
            - Path=/payment/lb/**

        #- id: video_routh
         # uri: https://www.bilibili.com/
          #predicates:
           # - Path=/bilibili/video

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
