server:
  port: 80

eureka:
  client:
    # 客户端只需要调用，不需要注册进eureka
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

# 设置openfeign的超时时间
ribbon:
  # 建立连接超时时间
  ReadTimeout: 5000
  # 请求服务端响应超时时间
  ConnectTimeout: 5000

logging:
  level:
    com.camille.springcloud.service.PaymentFeignService: debug

# 客户端开启服务容错
feign:
  hystrix:
    enabled: true