server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: # 配置绑定的rabbitmq的服务信息
        defaultRabbit:
          type: rabbit # 消息组件类型
          environment:  #设置rabbit的环境变量
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        input:
          destination: exchangeDemo
          content-type: application/json # 设置消息的类型为json
          binder: defaultRabbit

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 5 # 设置心跳时间间隔
    instance-id: receive-8802.com
    prefer-ip-address: true